import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { start_sort, preferences } from "../assets/scripts/sorting";
import { useState } from "react";
console.log(preferences);
export default function Home() {
  const [current_preference, set_preference] = useState(0);
  const [current_groups, set_groups] = useState({
    is_successful: false,
    payload: { data: "", standard_deviation: 0 },
  });
  let Group_List;
  if (current_groups.is_successful) {
    Group_List = Object.values(
      Object.values(current_groups.payload.data)[0]
    ).map((group, i) => {
      console.log(group);
      if (group.length) {
        const People = group.map((person) => (
          <p>
            {person[0]} | Aptitude: {person[1]}
          </p>
        ));
        return (
          <div>
            <h1>Group {i + 1}</h1>
            {People}
          </div>
        );
      }
    });
  }
  console.log(Group_List);
  const Preference_List = Object.keys(preferences).map((preference, i) => (
    <div
      style={{
        border:
          (i == current_preference ? "3px" : "1px") +
          " solid " +
          (i == current_preference ? "blue" : "black"),
        padding: "6px",
        borderRadius: "25px",
        margin: "2px",
        userSelect: "none",
        cursor: "pointer",
      }}
      onClick={() => {
        set_preference(i);
      }}
    >
      {preference}
    </div>
  ));
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Group Sorter</h1>
        <h2>Select Category</h2>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
            flexDirection: "column",
          }}
        >
          {Preference_List}
        </div>
        <div
          style={{
            display: "flex",
            alignItems: "center",
            justifyContent: "center",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              justifyContent: "center",
              flexDirection: "column",
              margin: "10px",
            }}
          >
            <h3 style={{ marginBottom: "0px" }}>Threshold</h3>
            <input id="threshold" placeholder="7" style={{ width: "20px" }} />
            <button
              onClick={({ target }) => {
                target.disabled = true;
                let threshold = document.getElementById("threshold").value;
                let data = start_sort(parseInt(threshold), current_preference);
                console.log(data);
                target.disabled = false;
                set_groups(data);
                //console.log(group_listings);
              }}
            >
              Sort!
            </button>
          </div>
          <div
            style={{
              display: "flex",
              alignContent: "center",
              flexDirection: "column",
              justifyContent: "center",
            }}
          >
            <h3 style={{ marginBottom: "2px" }}>Standard Deviation</h3>
            <h2
              style={{
                display: "flex",
                alignContent: "center",
                justifyContent: "center",
              }}
              id="standard_deviation"
            >
              {Math.round(100 * current_groups.payload.standard_deviation) /
                100}
            </h2>
          </div>
          <p>
            {current_groups.is_successful ? "" : current_groups.payload.data}
          </p>
        </div>
        <p>Try to lower the threshold</p>
        <h1>Groups</h1>
        <div>{current_groups.is_successful ? Group_List : "No Groups"}</div>
      </main>

      <footer className={styles.footer}></footer>
    </div>
  );
}
